class Group < ActiveRecord::Base
  has_many :group_members, dependent: :destroy
  has_many :members, through: :group_members

  attr_accessible :name
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: groups
#
# * id         :integer         not null
#   name       :string(255)
#   created_at :datetime
#   updated_at :datetime
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
