class MeetingMember < ActiveRecord::Base
  belongs_to :member
  belongs_to :meeting
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: meeting_members
#
# * id         :integer         not null
#   member_id  :integer
#   meeting_id :integer
#   created_at :datetime
#   updated_at :datetime
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
