class Meeting < ActiveRecord::Base
  has_many :meeting_members
  has_many :members, through: :meeting_members

  attr_accessible :member_ids
  accepts_nested_attributes_for :members

  # put everyone in a group, draw connections as edges
  # rank by edges
  # pick first by rank
  # pick second by rank that isn't connected to first
  # pick third by rank that isn't connected to either first or second
  def self.schedule_all
    ranks = Hash[Member.all.map do |member|
      edge_ids = member.edge_ids
      [member.id, {edges: edge_ids, num_edges: edge_ids.count}]
    end]

    until ranks.empty?
      meeting_member_ids = []
      forbidden_member_ids = []
      until meeting_member_ids.length == 3
        pair = self.delete_max_rank(forbidden_member_ids, ranks)
        next if pair.nil?
        meeting_member_ids << pair.first
        forbidden_member_ids.concat(pair.last[:edges])
      end
      Meeting.create(member_ids: meeting_member_ids, meeting_date: self.choose_date(meeting_member_ids))
    end
  end

  def self.trigger_weekly_email
    time_range = (3.days.ago..Time.now)
    Meeting.where(created_at: time_range).each do |meeting|
      MemberMailer.new_meeting(meeting).deliver
    end
  end

  def self.trigger_weekly_debug_email
    time_range = (3.days.ago..Time.now)
    Meeting.where(created_at: time_range).each do |meeting|
      MemberMailer.new_meeting(meeting).deliver
    end
  end

  # TODO check calendars of members
  def self.choose_date(member_ids)
    nearest_monday = Date.commercial(Date.today.year, 1+Date.today.cweek, 1)
    nearest_monday + rand(6).days
  end

  # mutates ranks!
  def self.delete_max_rank(restricted_ids_arr, rem_ranks)
    rem_ranks_copy = rem_ranks.dup
    restricted_ids_arr.each { |r_id| rem_ranks_copy.delete(r_id) }

    if rem_ranks_copy.empty?
      nil
    else
      p_id, p_h = rem_ranks_copy.max_by do |id, h|
        if restricted_ids_arr.include?(id)
          next
        else
          h[:num_edges]
        end
      end
      rem_ranks.delete(p_id)
      [p_id, p_h]
    end
  end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: meetings
#
# * id           :integer         not null
#   meeting_date :date
#   created_at   :datetime
#   updated_at   :datetime
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
