class Member < ActiveRecord::Base
  MAX_GROUPS = 5

  has_many(
    :group_members,
    class_name: 'GroupMember',
    foreign_key: :member_id,
    primary_key: :id,
    dependent: :destroy
  )
  has_many(
    :groups,
    through: :group_members,
    source: :group
  )

  has_many :meeting_members, dependent: :destroy
  has_many :meetings, through: :meeting_members

  validates :groups, length: { in: 1..MAX_GROUPS,
                               too_short: ': you must be a part of at least %{count} group.',
                               too_long: ': you may be a part of at most %{count} groups.' }
  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of :email
  # The poor placement of this method is intentional
  def self.email_regexp
    s = ENV['COMPANY_MEMBER_EMAIL_REGEXP'] unless ENV['RAILS_ENV'] == 'test'
    s ? Regexp.new(s) : /.*/
  end
  validates_format_of :email, with: Member.email_regexp

  attr_accessible :name, :email, :group_ids, :left_out, :skip_meetings
  accepts_nested_attributes_for :groups

  before_save :default_values

  def default_values
    self.skip_meetings ||= false
    true
  end

  def to_s
    name
  end

  def first_name
    name =~ /\s/ ? name.split(' ').first : name
  end

  def self.active
    Member.where(skip_meetings: false)
  end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: members
#
# * id            :integer         not null
#   name          :string(255)
#   email         :string(255)
#   created_at    :datetime
#   updated_at    :datetime
#   left_out      :boolean
#   skip_meetings :boolean         not null
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++
